"""add description to meeting

Revision ID: 786c196da9cc
Revises: 5cea1de93ec5
Create Date: 2026-05-12 17:48:01.976390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786c196da9cc'
down_revision: Union[str, Sequence[str], None] = '5cea1de93ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('description', sa.String(length=1000), nullable=True))
    op.alter_column('meetings', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('meetings', 'description')
    # ### end Alembic commands ###
