"""add period stop time to meetings

Revision ID: b2e3f7a1c8d9
Revises: 786c196da9cc
Create Date: 2026-06-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e3f7a1c8d9'
down_revision: Union[str, Sequence[str], None] = '786c196da9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('period_stop_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'period_stop_time')
    # ### end Alembic commands ###
